schemas = {
    "book": {
        "api_endpoint": "v1/books",
        "attributes": [
            "slug",
            "title",
            "summary",
            "author",
            "release_date",
            "dedication",
            "pages",
            "cover",
            "wiki",
        ],
    },
    "chapter": {
        "api_endpoint": "v1/books/{id}/chapters",
        "id_ref": "book",
        "attributes": [
            "slug",
            "order",
            "summary",
            "title",
        ],
    },
    "character": None,
    "movie": None,
    "potion": {
        "api_endpoint": "v1/potions",
        "api_query": {"page[size]": 100},
        "attributes": [
            "slug",
            "name",
            "effect",
            "side_effects",
            "characteristics",
            "time",
            "difficulty",
            "ingredients",
            "inventors",
            "manufacturers",
            "image",
            "wiki",
        ],
    },
    "spell": {
        "api_endpoint": "v1/spells",
        "api_query": {"page[size]": 100},
        "attributes": [
            "slug",
            "name",
            "incantation",
            "category",
            "effect",
            "light",
            "hand",
            "creator",
            "image",
            "wiki",
        ],
    },
}
